### ISSUE TITLE
[Question] How to setup to work alongside a Pi-hole container?

### ISSUE THREAD

**Issue by kibner** [klutchell/dnscrypt-proxy#22]
I have a fully working Pi-hole Docker container (https://github.com/pi-hole/docker-pi-hole) and want its upstream DNS server to point to this dnscrypt-proxy Docker container. I have tried using the IP address and appropriate port of both the host machine and the dnscrypt-proxy Docker container but that results in DNS requests not being resolved.

My `dnscrypt-proxy.toml` file is the same as the `example-dnscrypt-proxy.toml` file except with for changing the `listen_addresses` to `listen_addresses = ['0.0.0.0:53000']`.

I use `docker-compose` to run my containers. As a result, each container runs in bridge networking mode with their own, separate network. They are all on the same LAN (no VLAN on my network) and there have been no issues with my Plex Docker container (also on its own network) communicating with my Pi-hole Docker container. I have been able to run `docker-compose up` for dnscrypt-proxy and it appears to work looking at the log file below:

```
dnscrypt-proxy    | [2020-08-05 15:51:08] [NOTICE] dnscrypt-proxy 2.0.44
dnscrypt-proxy    | [2020-08-05 15:51:08] [NOTICE] Network connectivity detected
dnscrypt-proxy    | [2020-08-05 15:51:08] [NOTICE] Now listening to 0.0.0.0:53000 [UDP]
dnscrypt-proxy    | [2020-08-05 15:51:08] [NOTICE] Now listening to 0.0.0.0:53000 [TCP]
dnscrypt-proxy    | [2020-08-05 15:51:09] [NOTICE] Source [public-resolvers] loaded
dnscrypt-proxy    | [2020-08-05 15:51:09] [NOTICE] Source [relays] loaded
dnscrypt-proxy    | [2020-08-05 15:51:09] [NOTICE] Firefox workaround initialized
dnscrypt-proxy    | [2020-08-05 15:51:09] [NOTICE] [d0wn-tz-ns1] OK (DNSCrypt) - rtt: 237ms
[...]
dnscrypt-proxy    | [2020-08-05 15:52:17] [NOTICE] [dnscrypt.eu-dk] OK (DNSCrypt) - rtt: 133ms
dnscrypt-proxy    | [2020-08-05 15:52:17] [NOTICE] Sorted latencies:
dnscrypt-proxy    | [2020-08-05 15:52:17] [NOTICE] -     8ms nextdns
[...]
dnscrypt-proxy    | [2020-08-05 15:52:17] [NOTICE] -   317ms doh.ffmuc.net
dnscrypt-proxy    | [2020-08-05 15:52:17] [NOTICE] Server with the lowest initial latency: nextdns (rtt: 8ms)
dnscrypt-proxy    | [2020-08-05 15:52:17] [NOTICE] dnscrypt-proxy is ready - live servers: 61
```

dnscrypt-proxy `docker-compose.yaml` file:
```
services:
  dnscrypt-proxy:
    container_name: dnscrypt-proxy
    image: klutchell/dnscrypt-proxy:latest
    ports:
      - "53000:53000/udp"
      - "53000:53000/tcp"
    volumes:
      - ./docker-volumes/dnscrypt-proxy.toml:/config/dnscrypt-proxy.toml
    restart: unless-stopped

networks:
  default:
    external:
      name: dnscrypt-proxy
```

command used to create the `dnscrypt-proxy` external network:
```
docker network create --ipv6 --subnet "172.xx.xx.0/24" --subnet "fdxx:xxxx:xxxx:xxxx::/64" dnscrypt-proxy
```

The network for the pi-hole is similar to above, but with different subnets.
