### ISSUE TITLE
Configuration File Not Being Read

### ISSUE THREAD

**Issue by bigverm23** [klutchell/dnscrypt-proxy#32]
installed the docker container and mounted the config via:
 ```
 dnscrypt-proxy:
    image: klutchell/dnscrypt-proxy:latest
    container_name: dnscryptproxy
    restart: always
    ports:
      - "5053:53/udp"
    volumes:
      - $USERDIR/docker/dnscrypt-proxy/dnscrypt-proxy.toml:/config/dnscrypt-proxy.toml
    networks:
      traefik_web:
        ipv4_address: 172.21.0.43
```
Modified the server names to use Cisco: server_names = ['cisco', 'cisco-doh']

But on startup I see:
[2021-09-17 13:45:52] [NOTICE] Server with the lowest initial latency: uncensoreddns-ipv4 (rtt: 17ms)
[2021-09-17 13:45:52] [NOTICE] dnscrypt-proxy is ready - live servers: 123

Permission on the folder and toml file are nobody:nogroup 775
